<CovidStatusScreen>:
    FloatLayout:
        MDToolbar:
            md_bg_color: 0,0,0,0
            elevation: 0
            pos_hint: {"top": 1}
            left_action_items: [['chevron-left', lambda x: root.go_back()]]
            specific_text_color: 0,0,0,1

        MDLabel:
            id: currentstatus
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .800}
            text: ""

        MDTextField:
            id: covidstatus
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .500}
            hint_text: "Covid Status (Infected, Quarntined, Normal, Vaccinated)"


        MDFillRoundFlatButton:
            text: "Save"
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .200}
            on_release:
                app.update_covid_status(covidstatus.text)
                # root.parent.current = "main_screen"
            