#include firebaseloginscreen.kv
#:import firebaseloginscreen firebaseloginscreen.FirebaseLoginScreen
#:import utils kivy.utils

ScreenManager:
    id: screen_manager
    FirebaseLoginScreen:
        id: firebase_login_screen
        name: "firebase_login_screen"
        remember_user: True
        web_api_key: "AIzaSyDcrStnbgF8af01GqBRIX1GSLr7KZITgT0" # Found in Firebase -> Project Settings -> Web API Key
        background: "background.jpg"
        on_login_success:
            if self.login_state == 'in': print("User has logged in. Unique identifier is ", self.localId)
            if self.login_state == 'out': print("User signed out")
            if self.login_state == 'in': app.local_id = self.localId
            if self.login_state == 'in': app.user_idToken = self.idToken
            if self.login_state == 'in': app.display_user_tokens()
            if self.login_state == 'in': screen_manager.current = 'example_screen'

    Screen:
        id: example_screen
        name: "example_screen"
        BoxLayout:
            MDLabel:
                id: the_label
            MDRaisedButton:
                text: "Log out"
                on_release:
                    app.sign_out()
