#:import firebaseloginscreen firebaseloginscreen.FirebaseLoginScreen
#:import utils kivy.utils

ScreenManager:
    id: screen_manager
    FirebaseLoginScreen:
        id: firebase_login_screen
        name: "firebase_login_screen"
        remember_user: True
        web_api_key: "AIzaSyDcrStnbgF8af01GqBRIX1GSLr7KZITgT0" # Found in Firebase -> Project Settings -> Web API Key
        background: "background.jpg"
        on_login_success:
            if self.login_state == 'in': print("User has logged in. Unique identifier is ", self.localId)
            if self.login_state == 'out': print("User signed out")
            if self.login_state == 'in': app.local_id = self.localId
            if self.login_state == 'in': app.user_idToken = self.idToken
            # if self.login_state == 'in': app.getInfo()
            if self.login_state == 'in': app.display_covid_status()
            if self.login_state == 'in': app.get_assigned()
            if self.login_state == 'in': screen_manager.current = "main_screen"
    CovidStatusScreen:
        id: covid_status_screen
        name: "covid_status_screen"
    MainScreen:
        id: main_screen
        name: "main_screen"
    ProfilePageScreen:
        id: profile_page_screen
        name: "profile_page_screen"
    AppointmentScreen:
        id: appointment_screen
        name: "appointment_screen"

