<MainScreen>:
    FloatLayout:
        MDToolbar:
            md_bg_color: 0,0,0,0
            elevation: 0
            pos_hint: {"top": 1}
            left_action_items: [['chevron-left', lambda x: root.go_back()]]
            right_action_item: [['chevron-down', lambda x: app.sign_out()]]
            specific_text_color: 0,0,0,1
        MDLabel:
            id: the_label
        MDFillRoundFlatButton:
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .100}
            text: "Log out"
            on_release:
                app.sign_out()
        MDFillRoundFlatButton:
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .500}
            text: "Update Profile"
            on_release:
                root.parent.current = 'profile_page_screen'
        MDFillRoundFlatButton:
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .600}
            text: "Update Covid-19 Status"
            on_release:
                root.parent.current = "covid_status_screen"
        MDFillRoundFlatButton:
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .400}
            text: "View Appointment"
            on_release:
                root.parent.current = "appointment_screen"
            