<ProfilePageScreen>:
    FloatLayout:
        MDToolbar:
            md_bg_color: 0,0,0,0
            elevation: 0
            pos_hint: {"top": 1}
            left_action_items: [['chevron-left', lambda x: root.go_back()]]
            specific_text_color: 0,0,0,1

        MDTextField:
            id: name
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .800}
            hint_text: "Name"

        MDTextField:    
            id: age
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .700}
            hint_text: "Age"

        MDTextField:
            id: phonenumber
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .600}
            hint_text: "Phone Number eg: 12345678"

        MDTextField:
            id: postcode
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .50}
            hint_text: "Post Code"

        MDTextField:
            id: occupation
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .400}
            hint_text: "Occupation (Healthcare, Community Service, Social Service, Teaching or Other)"
       
        MDTextField:
            id: covidstatus
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .300}
            hint_text: "Covid Status (Infected, Quarntined, Normal, Vaccinated)"

        MDTextField:    
            id: medicalcondition
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .200}
            hint_text: "Medical Conditions (Put N/A if none)"

        MDFillRoundFlatButton:
            text: "Save"
            size_hint_x: .9
            pos_hint: {"center_x": .5, "top": .100}
            on_release:
                app.update_profile(name.text, age.text, phonenumber.text, postcode.text, occupation.text, covidstatus.text, medicalcondition.text)
                # root.parent.current = "main_screen"